name: image_picker_android
description: Android implementation of the image_picker plugin.
repository: https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22

version: 0.8.8

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      android:
        package: io.flutter.plugins.imagepicker
        pluginClass: ImagePickerPlugin
        dartPluginClass: ImagePickerAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle:
    git:
      url: https://github.com/ibrahimMahfuz/packages.git
      path: packages/flutter_plugin_android_lifecycle
      ref: image-picker-2
  image_picker_platform_interface:
    git:
      url: https://github.com/ibrahimMahfuz/packages.git
      path: packages/image_picker/image_picker_platform_interface
      ref: image-picker-2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.1
  pigeon: ^9.2.5

topics:
  - camera
  - image-picker
  - files
  - file-selection
