name: image_picker
description: Flutter plugin for selecting images from the Android and iOS image
  library, and taking new pictures with the camera.
repository: https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 1.0.4

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: image_picker_android

dependencies:
  flutter:
    sdk: flutter
  image_picker_android:
    git:
      url: https://github.com/ibrahimMahfuz/packages.git
      path: packages/image_picker/image_picker_android
      ref: image-picker-1
  image_picker_platform_interface:
    git:
      url: https://github.com/ibrahimMahfuz/packages.git
      path: packages/image_picker/image_picker_platform_interface
      ref: image-picker-1


dev_dependencies:
  build_runner: ^2.1.10
  cross_file: ^0.3.1+1 # Mockito generates a direct include.
  flutter_test:
    sdk: flutter
  mockito: 5.4.1
  plugin_platform_interface:
    git:
      url: https://github.com/ibrahimMahfuz/packages.git
      path: packages/plugin_platform_interface
      ref: image-picker-1

topics:
  - camera
  - image-picker
  - files
  - file-selection
